# Excluir solicitudes POST de la redirección para que Netlify Forms las maneje
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { "Method" = ["GET"] }

[build]
  command = ""
  publish = "."